services:
  edge:
    image: inductiveautomation/ignition:8.1.45
    hostname: edge
    ports:
      - 9088:8088
    volumes:
      - edge-data:/usr/local/bin/ignition/data
    networks:
      - edge-network
    environment:
      - IGNITION_EDITION=edge
      - GATEWAY_ADMIN_PASSWORD=katlego
      - ACCEPT_IGNITION_EULA=Y
    command: >
      -n edge-gateway
      -m 2048
networks:
  edge-network:
volumes:
  edge-data: